### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by tf** [codevise/pageflow-react#1]
The usage section inside the readme is still empty. We should add guides for common tasks.
- [x] Guide: Creating page types (#7)
- [x] Guide: Creating widget types (#7)
- [x] Guide: Getting data with resolvers (#7)
- [ ] Reference: Generate inline doc for reusable components. [doclets.io](https://doclets.io/tf/pageflow-react) seems to support ES2015 and JSX now.
